# Generated by Django 3.2.19 on 2023-05-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_date', models.DateField()),
                ('act_time_begin', models.TimeField()),
                ('act_time_end', models.TimeField()),
                ('status', models.CharField(default='Состоится', max_length=20, verbose_name=False)),
                ('clients', models.ManyToManyField(to='trainers.Client')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trainers.trainer')),
            ],
        ),
    ]
