# Generated by Django 3.2.19 on 2023-05-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(default='Состоится', max_length=20),
        ),
    ]
