# Generated by Django 3.2.20 on 2023-07-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_alter_team_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Sports',
        ),
    ]
