# Generated by Django 3.2.20 on 2023-07-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0007_auto_20230718_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='sport_type',
        ),
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
