# Generated by Django 3.2.20 on 2023-07-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0008_auto_20230718_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='sport',
        ),
    ]
