# Generated by Django 3.2.20 on 2023-07-24 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0011_auto_20230718_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainers.sport'),
        ),
    ]
