# Generated by Django 3.2.20 on 2023-07-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0012_trainer_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='sport',
        ),
        migrations.AddField(
            model_name='trainer',
            name='sports',
            field=models.ManyToManyField(to='trainers.Sport'),
        ),
    ]
